---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    # Deploy public assets
    - /bin/cp -R public/build $DEPLOYPATH
    - /bin/cp -R public/css $DEPLOYPATH
    - /bin/cp -R public/fonts $DEPLOYPATH
    - /bin/cp -R public/images $DEPLOYPATH
    - /bin/cp -R public/js $DEPLOYPATH
    - /bin/cp -R public/vendor $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH
    - /bin/cp public/favicon* $DEPLOYPATH
    - /bin/cp public/android-chrome* $DEPLOYPATH
    - /bin/cp public/apple-touch-icon.png $DEPLOYPATH
    - /bin/cp public/robots.txt $DEPLOYPATH
    - /bin/cp public/site.webmanifest $DEPLOYPATH
    - /bin/cp public/index.php $DEPLOYPATH

    # Deploy application files
    - export APPPATH=/home/example/
    - /bin/cp -R app $APPPATH
    - /bin/cp -R bootstrap $APPPATH
    - /bin/cp -R config $APPPATH
    - /bin/cp -R database $APPPATH
    - /bin/cp -R resources $APPPATH
    - /bin/cp -R routes $APPPATH
    - /bin/cp -R storage $APPPATH
    - /bin/cp .env.example $APPPATH.env
    - /bin/cp artisan $APPPATH
    - /bin/cp composer.json $APPPATH
    - /bin/cp composer.lock $APPPATH
