---
deployment:
  tasks:
    - export DEPLOYPATH=/home/recodexi/public_html/public
    # Deploy public assets
    - /bin/cp -R build $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp favicon* $DEPLOYPATH
    - /bin/cp android-chrome* $DEPLOYPATH
    - /bin/cp apple-touch-icon.png $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp site.webmanifest $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH

    # Deploy application files
    - export APPPATH=/home/recodexi/public_html/
    - /bin/cp -R app $APPPATH
    - /bin/cp -R bootstrap $APPPATH
    - /bin/cp -R config $APPPATH
    - /bin/cp -R database $APPPATH
    - /bin/cp -R resources $APPPATH
    - /bin/cp -R routes $APPPATH
    - /bin/cp -R storage $APPPATH
    - /bin/cp .env.example $APPPATH.env
    - /bin/cp artisan $APPPATH
    - /bin/cp composer.json $APPPATH
    - /bin/cp composer.lock $APPPATH